### ISSUE TITLE
Interview resource

### ISSUE THREAD

**Issue by zriyans** [Jiganesh/High-On-DSA#85]
Hey, @Jiganesh great work. 
I have something related to DSA, often asked in the interviews, if it fits this repo needs, you may include it. 

[Data Structure and Algorithms in real life](https://medium.com/interviewnoodle/data-structures-and-algorithms-in-real-life-6b2b813d516e)

This is written by me, a Medium Article.
Thanks

**Comment by Jiganesh** [comment]
Thanks @zriyans I created separate section and added the article. In README.md -> Resources Worth Reading. Its actually very good and I believe it will help others. The article is very fun to go through XD
Also please feel free to create a pull request and add other such articles.

Good Work !
